import os

# API Keys
DEEPSEEK_API_KEY = "sk-324c3796d9304113a43eefa9a437ba5c"

# Flask Config
SECRET_KEY = os.urandom(24)

# OAuth Config
GOOGLE_ID = "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_SECRET = "YOUR_GOOGLE_CLIENT_SECRET"
FACEBOOK_ID = "YOUR_FACEBOOK_APP_ID"
FACEBOOK_SECRET = "YOUR_FACEBOOK_APP_SECRET"
